### ISSUE TITLE
Create a Crop Description Document

### ISSUE THREAD

**Issue by pda0004** [pda0004/Case-Studies-Case-2-Team-1#16]
Include each crop we'll look at, how much it costs to plant, how much space each plant takes up, and any other relevant information. Edit doc at this link:

https://docs.google.com/document/d/1kzC8mNmnCGYz0vN0czud4qODSllLa7hrRye4tIg9K8s/edit?usp=sharing

**Comment by muthusm** [comment]
https://github.com/pda0004/Case-Studies-Case-2-Team-1/blob/main/data/Crop_Details.csv
