### ISSUE TITLE
Search for outside data that could be useful to augment our data

### ISSUE THREAD

**Issue by pda0004** [pda0004/Case-Studies-Case-2-Team-1#5]
We will need to have more data than is available in just our original dataset. This issue will mean finding other datasets that we could potentially use and describing them

**Comment by Yilin-Ye** [comment]
https://www.kaggle.com/srinivas1/agricuture-crops-production-in-india?select=datafile.csv

https://www.kaggle.com/thammuio/all-agriculture-related-datasets-for-india
